### ISSUE TITLE
Copiar os códigos de <header> e <footer> para dentro da página .html

### ISSUE THREAD

**Issue by thiagoManfredi** [ViniciusSumy/projeto_cine#10]
Cada integrante deve copiar os códigos de <header> e <footer> para dentro da página que criou.
 (Seguir a estrutura "<header><main><footer>" dentro de <body>)

**Comment by edvansabino** [comment]
A estrutura inicial do header e footer foram inseridas no arquivo HTML da home page e estão atualizados até o momento no repositório da organização.
